options:
  formatter: stylish
  # Merge default rules - override defaults with those specified in this config
  merge-default-rules: true
rules:
  bem-depth:
    - 2
    - max-depth: 1
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format: 0
  clean-import-paths: 0
  empty-line-between-blocks: 2
  extends-before-declarations: 0
  extends-before-mixins: 0
  hex-notation: 2
  leading-zero: 0
  mixins-before-declarations: 0
  nesting-depth: 0
  no-color-literals: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 1
    - extra-properties:
        - composes
  no-qualifying-elements: 0
  no-url-protocols: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  property-sort-order: 0
  quotes:
    - 2
    - style: single
  variable-for-property:
    - 2
    -
      properties:
        - color
