export const LOADING_PAGE_1_DATA = 'LOADING_PAGE_1_DATA';
export const LOADING_PAGE_1_DATA_ERROR = 'LOADING_PAGE_1_DATA_ERROR';
export const PAGE_1_DATA_LOADED = 'PAGE_1_DATA_LOADED';
export const PAGE_1_DATA_ALREADY_LOADED = 'PAGE_1_DATA_ALREADY_LOADED';
